### ISSUE TITLE
Connecting through a Jump Server (optional_args)

### ISSUE THREAD

**Issue by SeglaSamaty** [nornir-automation/nornir_napalm#13]
Hi everyone,
I'm trying to connect to my ios net devices using Nornir_napalm plugin, Nornir and napalm with linux jump server in the middle. I know that I need the  "optional_args" dict to be passed to Napalm so as to set the ssh config for the underlying Netmiko lib.

Since I'm not using Napalm directly, how do I pass the "optional_args" to the Napalm via the plugin nornir_napalm ?

**Comment by ktbyers** [comment]
```yaml
device1:
  hostname: 192.168.1.1
  username: cisco
  password: cisco
  platform: ios
  connection_options:
    napalm:
       extras:
         optional_args:
           argument1: value1
```
            transport: 'telnet'
```
