### ISSUE TITLE
nornir_napalm with nxos_ssh platform requires invoke?

### ISSUE THREAD

**Issue by supertylerc** [nornir-automation/nornir_napalm#33]
Ran into a weird one today.  With the following config and inventory:

```yaml
---
# config.yaml
inventory:
  plugin: SimpleInventory
runner:
  plugin: threaded
  options:
    num_workers: 4

---
# hosts.yaml
example.dal:
  hostname: example.dal.example.com
  port: 22
  platform: nxos_ssh
```

And the following Python:

```python
import logging
import os

from nornir_napalm.plugins.tasks import napalm_get
from nornir import InitNornir

nr = InitNornir(config_file="config.yaml", inventory={
    "options": {
        "host_file": "hosts.yaml",
    },
})
nr.inventory.defaults.username = os.getenv("NORNIR_USERNAME")
nr.inventory.defaults.password = os.getenv("NORNIR_PASSWORD")
r = nr.run(task=napalm_get, getters=["config"], severity_level=logging.DEBUG)
```

I get a `ModuleNotFound` that `invoke` couldn't be found.  Confused why `invoke` would be necessary, I tried with straight `napalm`, using the following code:

```python
from napalm import get_network_driver

driver = get_network_driver('nxos_ssh')
device = driver('example.dal.example.com', os.getenv("NAPALM_USERNAME"), os.getenv("NAPALM_PASSWORD"))
device.open()
device.get_config()
```

The above code using `napalm` directly works flawlessly.  Using the `nxos` `platform` in `nornir_napalm` works without issue.  But, for some reason, using `nxos_ssh` `platform` in `nornir_napalm` requires `invoke` (at least in my testing).

After installing `invoke` package, `nornir_napalm` works without any problem.  I see it in the `Poetry.lock`, but I can't find any other references to it in this repo.

Versions of packages are below:

```bash
$ pip freeze | grep -i "nornir\|napalm"
napalm==4.0.0
nornir==3.3.0
nornir-napalm==0.3.0
```
