### ISSUE TITLE
It needs to be in `connection_options` format so for `groups.yaml` it would be similar to the following:

### ISSUE THREAD

**Issue by Uthmanbello** [nornir-automation/nornir_napalm#42]
It needs to be in `connection_options` format so for `groups.yaml` it would be similar to the following:

```yaml
my_group:
  platform: nxos
  connection_options:
    napalm:
      extras:
        optional_args:
          fast_cli: False
          secret: my_secret
```

_Originally posted by @ktbyers in https://github.com/nornir-automation/nornir_napalm/issues/17#issuecomment-916233266_
